name: Build executable
on:
  workflow_dispatch:
    inputs:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle wrapper
      run: |
        cd kotlin
        ./gradlew build
        unzip build/distributions/SnowflakeChecker-1.0-SNAPSHOT.zip -d .
        rm -rf ../compiled/*
        mv SnowflakeChecker-1.0-SNAPSHOT/* ../compiled
        cd ..
        git add compiled
        git config --local user.email "github-actions[bot]@none.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update binary"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
