name: Perform e2e tests
on:
  workflow_dispatch:
    inputs:
      client:
        required: true
        type: string
    secrets:
      gihubToken:
        required: true
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pack events in json
      run: |
        echo "${{ secrets.SNOWFLAKE_KEY }}" > snowflake.pem
        compiled/bin/SnowflakeChecker test ${{ github.event.repository.owner.login }} ${{ github.event.repository.name }} ${{ secrets.TOKEN_FOR_GITHUB }} snowflake.pem ${{ secrets.SNOWFLAKE_USER }} ${{ inputs.client }}
        filename=$(find . -type f -name "test-finish-*" | sed 's/^.\///')
        echo "artifact_name=$filename" >> "$GITHUB_ENV"
    - uses: actions/upload-artifact@v3
      with:
        path: ${{ env.artifact_name }}
        name: ${{ env.artifact_name }}
