name: Save test start
on:
  workflow_dispatch:
    inputs:
      sdkName:
        required: true
        type: string
      sdkVersion:
        required: true
        type: string
      nextAction:
        required: true
        type: string
      eventTimes:
        required: true
        type: string
      eventNames:
        required: true
        type: string
      eventProperties:
        required: true
        type: string
      eventHeaders:
        required: true
        type: string
      eventContexts:
        required: true
        type: string
    secrets:
      gihubToken:
        required: true
jobs:
  pack-events:
    runs-on: ubuntu-latest
    steps:
    - name: Pack events in json
      run: |
        ./compiled/bin/SnowflakeChecker save ${{ inputs.sdkName }} ${{ inputs.sdkVersion }} ${{ inputs.nextAction }} ${{ inputs.eventTimes }} ${{ inputs.eventNames }} ${{ inputs.eventProperties }} ${{ inputs.eventHeaders }} ${{ inputs.eventContexts }}
        ls -a compiled
        ls -a compiled/bin
